### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by RajChanchal** [Banuba/quickstart-ios-swift#1]
The app crashes on start.

<img width="1393" alt="Screen Shot 2020-08-17 at 8 14 37 PM" src="https://user-images.githubusercontent.com/7058465/90418608-645a3000-e0c6-11ea-9631-9a9472cfa9d3.png">

**Comment by bnb-ashershen** [comment]
Looks like you have missed BanubaSdk framework.
Please fill in our form on [banuba.com](https://www.banuba.com/face-filters-sdk) website, or contact us via info@banuba.com.
