### ISSUE TITLE
Smoothly switch between video and photo modes 

### ISSUE THREAD

**Issue by chrsp** [Banuba/quickstart-ios-swift#17]
Is it possible to provide an example where the camera button works both for photos and video, like it is in the Instagram app for example, where if I press the button it takes a photo and if the button is held a video is recorded?

It seems it's always needed to restart the EffectPlayer and the RenderTarget, which causes a micro "glitch" on the screen. It would be great if that change could be done more smoothly.

**Comment by isayeter** [comment]
same problem, did you find a solution? @chrsp

**Comment by sdk-banuba** [comment]
You should change renderMode to “.photo“ in the constructor of EffectPlayerConfiguration. You can also take video in this case.

This parameter (renderMode) will be eliminated in version 1.5.0 and you will be able to take video and photos without such switching.

**Comment by isayeter** [comment]
When will 1.5.0 be released? @sdk-banuba
