### ISSUE TITLE
This bundle is invalid. The bundle at path Payload/projectName.app/Frameworks/BNBSdkApi.framework has an invalid CFBundleIdentifier 'banuba.sdk.sdk_api' 

### ISSUE THREAD

**Issue by ChurikiTenna** [Banuba/quickstart-ios-swift#19]
Hi, 
I'm using Banuba sdk via cocoapods.
When I try to archive the project, it fails with 'This bundle is invalid' error.

full error message:
`
This bundle is invalid. The bundle at path Payload/projectName.app/Frameworks/BNBSdkApi.framework has an invalid CFBundleIdentifier 'banuba.sdk.sdk_api' There are invalid characters(characters that are not dots, hyphen and alphanumerics) that have been replaced with their code point 'banuba.sdk.sdk\u005fapi' CFBundleIdentifier must be present, must contain only alphanumerics, dots, hyphens and must not end with a dot. [see the Core Foundation Keys at https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102070-TPXREF105] With error code STATE_ERROR.VALIDATION_ERROR.90049 for id ea662143-ace7-418e-95e7-e72119f57bc9
`

podfile:
`pod 'BanubaSdk', '1.4.0'`

Am I not supposed to install sdk with cocoapods? Or am I doing something wrong?
Thank you for your time.

**Comment by AlexLatushko** [comment]
Hi @ChurikiTenna !

The problem arise when you choose Product -> Archive? Or there are some other actions to reproduce the issue?

**Comment by ChurikiTenna** [comment]
Thank you for your response @AlexLatushko !

Yes. The problem arise when I choose Product -> Archive.

**Comment by ChurikiTenna** [comment]
I've tried archiving quickstart-ios-swift itself, then it succeeded.
But I see warning on `import BNBSdkApi`.

`'/Users/tenna/Library/Developer/Xcode/DerivedData/quickstart-ios-swift-fcdaeuaudethshfyqqgtconfmzjq/Build/Intermediates.noindex/ArchiveIntermediates/quickstart-ios-swift/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/BNBSdkApi/BNBSdkApi.framework/Modules/BNBSdkApi.swiftmodule/Project/arm64-apple-ios.swiftsourceinfo' is either malformed or generated by a different Swift version. Note that it uses an unstable format and may leak internal project details, it should not be distributed alongside modules`

Hope that'll help..

**Comment by AlexLatushko** [comment]
@ChurikiTenna 
Could you please try pod version 1.4.1-1-gd5934a820f ? It must solve the problem with bundle.

**Comment by ChurikiTenna** [comment]
Thank you for checking @AlexLatushko !
I tried `pod 'BanubaSdk', '1.4.1-1-gd5934a820f'`, but I emit error below.
```
[!] CocoaPods could not find compatible versions for pod "BanubaSdk":
  In Podfile:
    BanubaSdk (= 1.4.1-1-gd5934a820f)

None of your spec sources contain a spec satisfying the dependency: `BanubaSdk (= 1.4.1-1-gd5934a820f)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by AlexLatushko** [comment]
@ChurikiTenna,

Could you please try to clone this example to new empty folder, replace pod for version 1.4.1-1-gd5934a820f and then build example  according to the readme?

**Comment by ChurikiTenna** [comment]
@AlexLatushko 

I cloned the example, and changed version to  1.4.1-1-gd5934a820f as below.
```
platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/sdk-banuba/banuba-sdk-podspecs.git'

target 'quickstart-ios-swift' do
  use_frameworks!

  pod 'BanubaSdk', '1.4.1-1-gd5934a820f'

  target 'quickstart-ios-swiftUITests' do
    inherit! :search_paths
  end
end
```

But it emit exact same error on pod install..
```
[!] CocoaPods could not find compatible versions for pod "BanubaSdk":
  In Podfile:
    BanubaSdk (= 1.4.1-1-gd5934a820f)

None of your spec sources contain a spec satisfying the dependency: `BanubaSdk (= 1.4.1-1-gd5934a820f)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by ChurikiTenna** [comment]
After `pod repo update`, I could install `1.4.1-1-gd5934a820f`!! And it worked!!
Sorry for the hassle.
Thank you so much for your support.

**Comment by AlexLatushko** [comment]
@ChurikiTenna,

thank you for your report!
