### ISSUE TITLE
Error installing BNBSdkCore

### ISSUE THREAD

**Issue by PiPyL** [Banuba/quickstart-ios-swift#20]
![image](https://user-images.githubusercontent.com/34052864/170182085-49a89be4-fa62-4a97-b428-ce83d9245dc6.png)

I meet issues in above image. Do you anyone help me? Thanks

**Comment by AlexLatushko** [comment]
Hello @PiPyL 

Do you use the up-to-date version of the master branch? If not, what pod version are you using?

Please, try to install pod version 1.4.1.

**Comment by sdk-banuba** [comment]
Closed due to inactivity.
